### ISSUE TITLE
Unit Test Cases for om_hospital Module

### ISSUE THREAD

**Issue by sean-delcastillo** [sean-delcastillo/CPSC-463-Software-Testing-Group-Project#4]
- [X] Make five unit test cases
- [x] Make three more unit test cases
- [X] Final: eleven test cases
- [ ] test_unlinked_allowed needs an assertion

**Comment by sean-delcastillo** [comment]
Added two test cases in 692a8231441e32d70509465f863a7c5456e1dbae that test the patient model's default behavior for the gender and reference attributes

**Comment by fbecerra07** [comment]
Added two test cases for doctor model in c8e3d7e. Tests default gender value and checks for negative appointment count associated with the doctor.

**Comment by KevinDelgad** [comment]
Added seven test cases for appointment model in commit 109cfe2 . Tests Appointment creation, Appointment confirmation, Appointment completion, Appointment Drafting, Appointment Cancellation, and Appointment unlinking.

**Comment by sean-delcastillo** [comment]
Bugfix on a doctor model test case 32ffb328fd6cf2a4a3b067e338ef22d3d4bf54c1. The test method was looking for a "name" field on the record but the doctor record defines a "doctor_name" field.
